FROM centos:centos7
MAINTAINER Daniel Miranda <danielkza2@gmail.com>

VOLUME /var/cache/yum
RUN sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf

RUN yum -y install epel-release
RUN yum -y upgrade
RUN yum -y install sudo git yum-utils rpmdevtools createrepo rsync make automake gcc gcc-c++ 

ADD doxyparse /root/analizo/doxyparse/
ADD analizo /root/analizo/analizo/
ADD deps /root/analizo/deps/

ADD analizo-local.repo /etc/yum.repos.d/
ADD build.sh /root/analizo/

WORKDIR /root/analizo
CMD ["/root/analizo/build.sh"]
